/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.border.AbstractBorder;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author Bel
 */
public class Recepción extends javax.swing.JFrame {

    /**
     * Creates new form Recepción
     */
    public Recepción() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelUnidad = new javax.swing.JPanel();
        textFieldInstitucion = new javax.swing.JTextField();
        textFieldDelegacion = new javax.swing.JTextField();
        textFieldJurisdiccion = new javax.swing.JTextField();
        textFieldMunicipio = new javax.swing.JTextField();
        textFieldUnidadMedica = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textFieldClavePaciente = new javax.swing.JTextField();
        textFieldApellidoPaterno = new javax.swing.JTextField();
        textFieldApellidoMaterno = new javax.swing.JTextField();
        textFieldNombres = new javax.swing.JTextField();
        textFieldEntidadNacimiento = new javax.swing.JTextField();
        textFieldCURP = new javax.swing.JTextField();
        textFieldEdad = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldServicioMedico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textFieldEscolaridad = new javax.swing.JTextField();
        textFieldOcupacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        textFieldLocalidad1 = new javax.swing.JTextField();
        textFieldColonia1 = new javax.swing.JTextField();
        textFieldDireccion1 = new javax.swing.JTextField();
        textFieldEntidadFederativa = new javax.swing.JTextField();
        textFieldDireccionJurisdiccion = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldDireccion2 = new javax.swing.JTextField();
        textFieldColonia2 = new javax.swing.JTextField();
        textFieldLocalidad2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        formattedTextFieldFecha = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldNSS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonGuardar = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1000, 750));

        panelBackground.setBackground(new java.awt.Color(228, 234, 253));
        panelBackground.setPreferredSize(new java.awt.Dimension(1000, 750));

        panelUnidad.setBackground(new java.awt.Color(255, 255, 255));
        panelUnidad.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Unidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 20))); // NOI18N

        textFieldInstitucion.setForeground(new java.awt.Color(153, 153, 255));
        textFieldInstitucion.setText("Institución");
        textFieldInstitucion.setToolTipText("");
        textFieldInstitucion.setBorder(new RoundedCornerBorder());
        textFieldInstitucion.setName(""); // NOI18N
        textFieldInstitucion.setOpaque(false);
        textFieldInstitucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldInstitucionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldInstitucionFocusLost(evt);
            }
        });

        textFieldDelegacion.setForeground(new java.awt.Color(153, 153, 255));
        textFieldDelegacion.setText("Entidad/Delegación");
        textFieldDelegacion.setBorder(new RoundedCornerBorder());
        textFieldDelegacion.setOpaque(false);
        textFieldDelegacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldDelegacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDelegacionFocusLost(evt);
            }
        });
        textFieldDelegacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldDelegacionKeyTyped(evt);
            }
        });

        textFieldJurisdiccion.setForeground(new java.awt.Color(153, 153, 255));
        textFieldJurisdiccion.setText("Jurisdicción");
        textFieldJurisdiccion.setBorder(new RoundedCornerBorder());
        textFieldJurisdiccion.setOpaque(false);
        textFieldJurisdiccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldJurisdiccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldJurisdiccionFocusLost(evt);
            }
        });

        textFieldMunicipio.setForeground(new java.awt.Color(153, 153, 255));
        textFieldMunicipio.setText("Municipio");
        textFieldMunicipio.setBorder(new RoundedCornerBorder());
        textFieldMunicipio.setOpaque(false);
        textFieldMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldMunicipioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldMunicipioFocusLost(evt);
            }
        });
        textFieldMunicipio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldMunicipioKeyTyped(evt);
            }
        });

        textFieldUnidadMedica.setForeground(new java.awt.Color(153, 153, 255));
        textFieldUnidadMedica.setText("Unidad Médica");
        textFieldUnidadMedica.setBorder(new RoundedCornerBorder());
        textFieldUnidadMedica.setOpaque(false);
        textFieldUnidadMedica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUnidadMedicaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldUnidadMedicaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelUnidadLayout = new javax.swing.GroupLayout(panelUnidad);
        panelUnidad.setLayout(panelUnidadLayout);
        panelUnidadLayout.setHorizontalGroup(
            panelUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnidadLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUnidadLayout.createSequentialGroup()
                        .addComponent(textFieldJurisdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(textFieldUnidadMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUnidadLayout.createSequentialGroup()
                        .addComponent(textFieldInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelUnidadLayout.setVerticalGroup(
            panelUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnidadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelUnidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldUnidadMedica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldJurisdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textFieldClavePaciente.setForeground(new java.awt.Color(153, 153, 255));
        textFieldClavePaciente.setText("Clave de la paciente");
        textFieldClavePaciente.setBorder(new RoundedCornerBorder());
        textFieldClavePaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldClavePacienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldClavePacienteFocusLost(evt);
            }
        });

        textFieldApellidoPaterno.setForeground(new java.awt.Color(153, 153, 255));
        textFieldApellidoPaterno.setText("Apellido Paterno");
        textFieldApellidoPaterno.setBorder(new RoundedCornerBorder());
        textFieldApellidoPaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldApellidoPaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldApellidoPaternoFocusLost(evt);
            }
        });
        textFieldApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldApellidoPaternoKeyTyped(evt);
            }
        });

        textFieldApellidoMaterno.setForeground(new java.awt.Color(153, 153, 255));
        textFieldApellidoMaterno.setText("Apellido Materno");
        textFieldApellidoMaterno.setBorder(new RoundedCornerBorder());
        textFieldApellidoMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldApellidoMaternoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldApellidoMaternoFocusLost(evt);
            }
        });
        textFieldApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldApellidoMaternoKeyTyped(evt);
            }
        });

        textFieldNombres.setForeground(new java.awt.Color(153, 153, 255));
        textFieldNombres.setText("Nombre(s)");
        textFieldNombres.setBorder(new RoundedCornerBorder());
        textFieldNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldNombresFocusLost(evt);
            }
        });
        textFieldNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNombresKeyTyped(evt);
            }
        });

        textFieldEntidadNacimiento.setForeground(new java.awt.Color(153, 153, 255));
        textFieldEntidadNacimiento.setText("Entidad de Nacimiento");
        textFieldEntidadNacimiento.setBorder(new RoundedCornerBorder());
        textFieldEntidadNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEntidadNacimientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEntidadNacimientoFocusLost(evt);
            }
        });

        textFieldCURP.setForeground(new java.awt.Color(153, 153, 255));
        textFieldCURP.setText("CURP");
        textFieldCURP.setBorder(new RoundedCornerBorder());
        textFieldCURP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldCURPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldCURPFocusLost(evt);
            }
        });

        textFieldEdad.setEditable(false);
        textFieldEdad.setForeground(new java.awt.Color(153, 153, 255));
        textFieldEdad.setText("Edad");
        textFieldEdad.setBorder(new RoundedCornerBorder());
        textFieldEdad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEdadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEdadFocusLost(evt);
            }
        });

        textFieldEmail.setForeground(new java.awt.Color(153, 153, 255));
        textFieldEmail.setText("Correo Electrónico");
        textFieldEmail.setToolTipText("");
        textFieldEmail.setBorder(new RoundedCornerBorder());
        textFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEmailFocusLost(evt);
            }
        });

        textFieldServicioMedico.setForeground(new java.awt.Color(153, 153, 255));
        textFieldServicioMedico.setText("Servicio Medico");
        textFieldServicioMedico.setBorder(new RoundedCornerBorder());
        textFieldServicioMedico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldServicioMedicoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldServicioMedicoFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel1.setText("Identificación");

        textFieldEscolaridad.setForeground(new java.awt.Color(153, 153, 255));
        textFieldEscolaridad.setText("Escolaridad");
        textFieldEscolaridad.setBorder(new RoundedCornerBorder());
        textFieldEscolaridad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEscolaridadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEscolaridadFocusLost(evt);
            }
        });

        textFieldOcupacion.setForeground(new java.awt.Color(153, 153, 255));
        textFieldOcupacion.setText("Ocupación");
        textFieldOcupacion.setToolTipText("");
        textFieldOcupacion.setBorder(new RoundedCornerBorder());
        textFieldOcupacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldOcupacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldOcupacionFocusLost(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(228, 234, 253), 1, true), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 20))); // NOI18N

        textFieldLocalidad1.setForeground(new java.awt.Color(153, 153, 255));
        textFieldLocalidad1.setText("Localidad/Municipio/Delegación");
        textFieldLocalidad1.setBorder(new RoundedCornerBorder());
        textFieldLocalidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldLocalidad1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldLocalidad1FocusLost(evt);
            }
        });

        textFieldColonia1.setForeground(new java.awt.Color(153, 153, 255));
        textFieldColonia1.setText("Colonia");
        textFieldColonia1.setBorder(new RoundedCornerBorder());
        textFieldColonia1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldColonia1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldColonia1FocusLost(evt);
            }
        });

        textFieldDireccion1.setForeground(new java.awt.Color(153, 153, 255));
        textFieldDireccion1.setText("Calle y Número");
        textFieldDireccion1.setBorder(new RoundedCornerBorder());
        textFieldDireccion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldDireccion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDireccion1FocusLost(evt);
            }
        });

        textFieldEntidadFederativa.setForeground(new java.awt.Color(153, 153, 255));
        textFieldEntidadFederativa.setText("Entidad Federativa");
        textFieldEntidadFederativa.setBorder(new RoundedCornerBorder());
        textFieldEntidadFederativa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldEntidadFederativaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldEntidadFederativaFocusLost(evt);
            }
        });

        textFieldDireccionJurisdiccion.setForeground(new java.awt.Color(153, 153, 255));
        textFieldDireccionJurisdiccion.setText("Jurisdicción");
        textFieldDireccionJurisdiccion.setBorder(new RoundedCornerBorder());
        textFieldDireccionJurisdiccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldDireccionJurisdiccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDireccionJurisdiccionFocusLost(evt);
            }
        });

        textFieldTelefono.setForeground(new java.awt.Color(153, 153, 255));
        textFieldTelefono.setText("Teléfono");
        textFieldTelefono.setBorder(new RoundedCornerBorder());
        textFieldTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldTelefonoFocusLost(evt);
            }
        });

        textFieldDireccion2.setForeground(new java.awt.Color(153, 153, 255));
        textFieldDireccion2.setText("Calle y Número");
        textFieldDireccion2.setBorder(new RoundedCornerBorder());
        textFieldDireccion2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldDireccion2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldDireccion2FocusLost(evt);
            }
        });

        textFieldColonia2.setForeground(new java.awt.Color(153, 153, 255));
        textFieldColonia2.setText("Colonia");
        textFieldColonia2.setBorder(new RoundedCornerBorder());
        textFieldColonia2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldColonia2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldColonia2FocusLost(evt);
            }
        });

        textFieldLocalidad2.setForeground(new java.awt.Color(153, 153, 255));
        textFieldLocalidad2.setText("Localidad/Municipio/Delegación");
        textFieldLocalidad2.setBorder(new RoundedCornerBorder());
        textFieldLocalidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldLocalidad2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldLocalidad2FocusLost(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(228, 234, 253));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel4.setText("Otra Dirección");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldDireccion1)
                    .addComponent(textFieldDireccion2)
                    .addComponent(textFieldEntidadFederativa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textFieldColonia1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldLocalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDireccionJurisdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldColonia2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(textFieldLocalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(textFieldEntidadFederativa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldLocalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldColonia1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldDireccionJurisdiccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldDireccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldColonia2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldLocalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        formattedTextFieldFecha.setBorder(new RoundedCornerBorder());
        formattedTextFieldFecha.setForeground(new java.awt.Color(153, 153, 255));
        formattedTextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        formattedTextFieldFecha.setToolTipText("Formato DD/MM/AAAA");
        formattedTextFieldFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTextFieldFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formattedTextFieldFechaFocusLost(evt);
            }
        });
        formattedTextFieldFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formattedTextFieldFechaKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Fecha de nacimiento");

        textFieldNSS.setForeground(new java.awt.Color(153, 153, 255));
        textFieldNSS.setText("No. Afiliación NSS");
        textFieldNSS.setBorder(new RoundedCornerBorder());
        textFieldNSS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldNSSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldNSSFocusLost(evt);
            }
        });
        textFieldNSS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNSSKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setText(" DD/MM/AAAA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldClavePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(formattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldEntidadNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldServicioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textFieldNSS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(textFieldApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(textFieldEntidadNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldClavePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldServicioMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formattedTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCURP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldEscolaridad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        buttonGuardar.setBackground(new java.awt.Color(102, 255, 102));
        buttonGuardar.setText("Guardar");
        buttonGuardar.setOpaque(false);

        buttonSalir.setBackground(new java.awt.Color(255, 51, 51));
        buttonSalir.setText("Salir");
        buttonSalir.setOpaque(false);
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283)
                        .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, 755, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldInstitucionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldInstitucionFocusGained
        if (textFieldInstitucion.getText().trim().equals("Institución")) {
            textFieldInstitucion.setText("");
        }

        textFieldInstitucion.setForeground(Color.red);

    }//GEN-LAST:event_textFieldInstitucionFocusGained

    private void textFieldInstitucionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldInstitucionFocusLost
        if (textFieldInstitucion.getText().trim().equals("")) {
            textFieldInstitucion.setText("Institución");
        }

        textFieldInstitucion.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldInstitucionFocusLost

    private void textFieldMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldMunicipioFocusGained
        if (textFieldMunicipio.getText().trim().equals("Municipio")) {
            textFieldMunicipio.setText("");
        }

        textFieldMunicipio.setForeground(Color.red);    }//GEN-LAST:event_textFieldMunicipioFocusGained

    private void textFieldMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldMunicipioFocusLost
        if (textFieldMunicipio.getText().trim().equals("")) {
            textFieldMunicipio.setText("Municipio");
        }

        textFieldMunicipio.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldMunicipioFocusLost

    private void textFieldDelegacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDelegacionFocusGained
        if (textFieldDelegacion.getText().trim().equals("Entidad/Delegación")) {
            textFieldDelegacion.setText("");
        }

        textFieldDelegacion.setForeground(Color.red);
    }//GEN-LAST:event_textFieldDelegacionFocusGained

    private void textFieldDelegacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDelegacionFocusLost
        if (textFieldDelegacion.getText().trim().equals("")) {
            textFieldDelegacion.setText("Entidad/Delegación");
        }

        textFieldDelegacion.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldDelegacionFocusLost

    private void textFieldUnidadMedicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUnidadMedicaFocusGained
        if (textFieldUnidadMedica.getText().trim().equals("Unidad Médica".trim())) {
            textFieldUnidadMedica.setText("");
        }

        textFieldUnidadMedica.setForeground(Color.red);
    }//GEN-LAST:event_textFieldUnidadMedicaFocusGained

    private void textFieldUnidadMedicaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUnidadMedicaFocusLost
        if (textFieldUnidadMedica.getText().trim().equals("")) {
            textFieldUnidadMedica.setText("Unidad Médica".trim());
        }

        textFieldUnidadMedica.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldUnidadMedicaFocusLost

    private void textFieldJurisdiccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldJurisdiccionFocusGained
        if (textFieldJurisdiccion.getText().trim().equals("Jurisdicción")) {
            textFieldJurisdiccion.setText("");
        }

        textFieldJurisdiccion.setForeground(Color.red);
    }//GEN-LAST:event_textFieldJurisdiccionFocusGained

    private void textFieldJurisdiccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldJurisdiccionFocusLost
        if (textFieldJurisdiccion.getText().trim().equals("")) {
            textFieldJurisdiccion.setText("Jurisdicción");
        }

        textFieldJurisdiccion.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldJurisdiccionFocusLost

    private void textFieldClavePacienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldClavePacienteFocusGained
        if (textFieldClavePaciente.getText().trim().equals("Clave de la paciente".trim())) {
            textFieldClavePaciente.setText("");
        }

        textFieldClavePaciente.setForeground(Color.red);
    }//GEN-LAST:event_textFieldClavePacienteFocusGained

    private void textFieldClavePacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldClavePacienteFocusLost
        if (textFieldClavePaciente.getText().trim().equals("")) {
            textFieldClavePaciente.setText("Clave de la paciente");
        }

        textFieldClavePaciente.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldClavePacienteFocusLost

    private void textFieldNSSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNSSFocusGained
        if (textFieldNSS.getText().trim().equals("No. Afiliación NSS".trim())) {
            textFieldNSS.setText("");
        }

        textFieldNSS.setForeground(Color.red);    }//GEN-LAST:event_textFieldNSSFocusGained

    private void textFieldNSSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNSSFocusLost
        if (textFieldNSS.getText().trim().equals("")) {
            textFieldNSS.setText("No. Afiliación NSS");
        }

        textFieldNSS.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldNSSFocusLost

    private void textFieldServicioMedicoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldServicioMedicoFocusGained
        if (textFieldServicioMedico.getText().trim().equals("Servicio Medico".trim())) {
            textFieldServicioMedico.setText("");
        }

        textFieldServicioMedico.setForeground(Color.red);
    }//GEN-LAST:event_textFieldServicioMedicoFocusGained

    private void textFieldServicioMedicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldServicioMedicoFocusLost
        if (textFieldServicioMedico.getText().trim().equals("")) {
            textFieldServicioMedico.setText("Servicio Medico");
        }

        textFieldServicioMedico.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldServicioMedicoFocusLost

    private void textFieldApellidoPaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldApellidoPaternoFocusGained
        if (textFieldApellidoPaterno.getText().trim().equals("Apellido Paterno".trim())) {
            textFieldApellidoPaterno.setText("");
        }

        textFieldApellidoPaterno.setForeground(Color.red);
    }//GEN-LAST:event_textFieldApellidoPaternoFocusGained

    private void textFieldApellidoPaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldApellidoPaternoFocusLost
        if (textFieldApellidoPaterno.getText().trim().equals("")) {
            textFieldApellidoPaterno.setText("Apellido Paterno");
        }

        textFieldApellidoPaterno.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldApellidoPaternoFocusLost

    private void textFieldApellidoMaternoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldApellidoMaternoFocusGained
        if (textFieldApellidoMaterno.getText().trim().equals("Apellido Materno".trim())) {
            textFieldApellidoMaterno.setText("");
        }

        textFieldApellidoMaterno.setForeground(Color.red);
    }//GEN-LAST:event_textFieldApellidoMaternoFocusGained

    private void textFieldApellidoMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldApellidoMaternoFocusLost
        if (textFieldApellidoMaterno.getText().trim().equals("")) {
            textFieldApellidoMaterno.setText("Apellido Materno");
        }

        textFieldApellidoMaterno.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldApellidoMaternoFocusLost

    private void textFieldNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNombresFocusGained
        if (textFieldNombres.getText().trim().equals("Nombre(s)")) {
            textFieldNombres.setText("");
        }

        textFieldNombres.setForeground(Color.red);
    }//GEN-LAST:event_textFieldNombresFocusGained

    private void textFieldNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldNombresFocusLost
        if (textFieldNombres.getText().trim().equals("")) {
            textFieldNombres.setText("Nombre(s)");
        }

        textFieldNombres.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldNombresFocusLost

    private void formattedTextFieldFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTextFieldFechaFocusGained
        if (formattedTextFieldFecha.getText().trim().equals("DD/MM/AAAA")) {
            formattedTextFieldFecha.setText("");
        }

        String text = formattedTextFieldFecha.getText().trim();
        //String regex = "(0?[1-9]|[12][0-9]|3[01])-(0?[1-9]|1[012])-((18|19|20|21)\\d\\d)";
        String regex2 = "^(?:3[01]|[12][0-9]|0?[1-9])([\\/])(0?[1-9]|1[1-2])\\1\\d{4}$";
        if(text != null && text != ""){
            if(!text.matches(regex2)){
            formattedTextFieldFecha.setText("");
            }
        }
        formattedTextFieldFecha.setForeground(Color.red);
    }//GEN-LAST:event_formattedTextFieldFechaFocusGained

    private void formattedTextFieldFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formattedTextFieldFechaFocusLost
        if (formattedTextFieldFecha.getText().trim().equals("")) {
            //formattedTextFieldFecha.setText("15/1/1900");
        }

        if (formattedTextFieldFecha.getText().trim() != null && !formattedTextFieldFecha.getText().trim().equals("")) {
            String aux = formattedTextFieldFecha.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date d;
            try {
                d = sdf.parse(aux);
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(d);
                int year = calendar.get(Calendar.YEAR);
                int month = calendar.get(Calendar.MONTH) + 1;
                int date = calendar.get(Calendar.DATE);
                LocalDate l1 = LocalDate.of(year, month, date);
                LocalDate now1 = LocalDate.now();
                Period diff1 = Period.between(l1, now1);
                textFieldEdad.setText(diff1.getYears() + "");
                textFieldEdad.setForeground(new Color(153, 153, 255));
            } catch (ParseException ex) {
                Logger.getLogger(Recepción.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        formattedTextFieldFecha.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_formattedTextFieldFechaFocusLost

    private void textFieldEdadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEdadFocusGained
        /*
        if (textFieldEdad.getText().trim().equals("Edad")) {
            textFieldEdad.setText("");
        }

        textFieldEdad.setForeground(Color.red);
         */
    }//GEN-LAST:event_textFieldEdadFocusGained

    private void textFieldEdadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEdadFocusLost
        /*
        if (textFieldEdad.getText().trim().equals("")) {
            textFieldEdad.setText("Edad");
        }

        textFieldEdad.setForeground(new Color(153, 153, 255));
         */
    }//GEN-LAST:event_textFieldEdadFocusLost

    private void textFieldEntidadNacimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEntidadNacimientoFocusGained
        if (textFieldEntidadNacimiento.getText().trim().equals("Entidad de Nacimiento".trim())) {
            textFieldEntidadNacimiento.setText("");
        }

        textFieldEntidadNacimiento.setForeground(Color.red);
    }//GEN-LAST:event_textFieldEntidadNacimientoFocusGained

    private void textFieldEntidadNacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEntidadNacimientoFocusLost
        if (textFieldEntidadNacimiento.getText().trim().equals("")) {
            textFieldEntidadNacimiento.setText("Entidad de Nacimiento");
        }

        textFieldEntidadNacimiento.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldEntidadNacimientoFocusLost

    private void textFieldCURPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCURPFocusGained
        if (textFieldCURP.getText().trim().equals("CURP")) {
            textFieldCURP.setText("");
        }

        textFieldCURP.setForeground(Color.red);
    }//GEN-LAST:event_textFieldCURPFocusGained

    private void textFieldCURPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldCURPFocusLost
        if (textFieldCURP.getText().trim().equals("")) {
            textFieldCURP.setText("CURP");
        }

        textFieldCURP.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldCURPFocusLost

    private void textFieldEscolaridadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEscolaridadFocusGained
        if (textFieldEscolaridad.getText().trim().equals("Escolaridad")) {
            textFieldEscolaridad.setText("");
        }

        textFieldEscolaridad.setForeground(Color.red);
    }//GEN-LAST:event_textFieldEscolaridadFocusGained

    private void textFieldEscolaridadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEscolaridadFocusLost
        if (textFieldEscolaridad.getText().trim().equals("")) {
            textFieldEscolaridad.setText("Escolaridad");
        }

        textFieldEscolaridad.setForeground(new Color(153, 153, 255));    }//GEN-LAST:event_textFieldEscolaridadFocusLost

    private void textFieldOcupacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldOcupacionFocusGained
        if (textFieldOcupacion.getText().trim().equals("Ocupación")) {
            textFieldOcupacion.setText("");
        }

        textFieldOcupacion.setForeground(Color.red);
    }//GEN-LAST:event_textFieldOcupacionFocusGained

    private void textFieldOcupacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldOcupacionFocusLost
        if (textFieldOcupacion.getText().trim().equals("")) {
            textFieldOcupacion.setText("Ocupación");
        }

        textFieldOcupacion.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldOcupacionFocusLost

    private void textFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailFocusGained
        if (textFieldEmail.getText().trim().equals("Correo Electrónico".trim())) {
            textFieldEmail.setText("");
        }

        textFieldEmail.setForeground(Color.red);
    }//GEN-LAST:event_textFieldEmailFocusGained

    private void textFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEmailFocusLost
        if (textFieldEmail.getText().trim().equals("")) {
            textFieldEmail.setText("Correo Electrónico");
        }

        textFieldEmail.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldEmailFocusLost

    private void textFieldDireccion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccion1FocusGained
        if (textFieldDireccion1.getText().trim().equals("Calle y Número".trim())) {
            textFieldDireccion1.setText("");
        }

        textFieldDireccion1.setForeground(Color.red);
    }//GEN-LAST:event_textFieldDireccion1FocusGained

    private void textFieldDireccion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccion1FocusLost
        if (textFieldDireccion1.getText().trim().equals("")) {
            textFieldDireccion1.setText("Calle y Número");
        }

        textFieldDireccion1.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldDireccion1FocusLost

    private void textFieldColonia1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldColonia1FocusGained
        if (textFieldColonia1.getText().trim().equals("Colonia")) {
            textFieldColonia1.setText("");
        }

        textFieldColonia1.setForeground(Color.red);
    }//GEN-LAST:event_textFieldColonia1FocusGained

    private void textFieldColonia1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldColonia1FocusLost
        if (textFieldColonia1.getText().trim().equals("")) {
            textFieldColonia1.setText("Colonia");
        }

        textFieldColonia1.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldColonia1FocusLost

    private void textFieldLocalidad1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldLocalidad1FocusGained
        if (textFieldLocalidad1.getText().trim().equals("Localidad/Municipio/Delegación")) {
            textFieldLocalidad1.setText("");
        }

        textFieldLocalidad1.setForeground(Color.red);
    }//GEN-LAST:event_textFieldLocalidad1FocusGained

    private void textFieldLocalidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldLocalidad1FocusLost
        if (textFieldLocalidad1.getText().trim().equals("")) {
            textFieldLocalidad1.setText("Localidad/Municipio/Delegación");
        }

        textFieldLocalidad1.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldLocalidad1FocusLost

    private void textFieldEntidadFederativaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEntidadFederativaFocusGained
        if (textFieldEntidadFederativa.getText().trim().equals("Entidad Federativa".trim())) {
            textFieldEntidadFederativa.setText("");
        }

        textFieldEntidadFederativa.setForeground(Color.red);
    }//GEN-LAST:event_textFieldEntidadFederativaFocusGained

    private void textFieldEntidadFederativaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldEntidadFederativaFocusLost
        if (textFieldEntidadFederativa.getText().trim().equals("")) {
            textFieldEntidadFederativa.setText("Entidad Federativa");
        }

        textFieldEntidadFederativa.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldEntidadFederativaFocusLost

    private void textFieldDireccionJurisdiccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccionJurisdiccionFocusGained
        if (textFieldDireccionJurisdiccion.getText().trim().equals("Jurisdicción")) {
            textFieldDireccionJurisdiccion.setText("");
        }

        textFieldDireccionJurisdiccion.setForeground(Color.red);
    }//GEN-LAST:event_textFieldDireccionJurisdiccionFocusGained

    private void textFieldDireccionJurisdiccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccionJurisdiccionFocusLost
        if (textFieldDireccionJurisdiccion.getText().trim().equals("")) {
            textFieldDireccionJurisdiccion.setText("Jurisdicción");
        }

        textFieldDireccionJurisdiccion.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldDireccionJurisdiccionFocusLost

    private void textFieldTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldTelefonoFocusGained
        if (textFieldTelefono.getText().trim().equals("Teléfono")) {
            textFieldTelefono.setText("");
        }

        textFieldTelefono.setForeground(Color.red);
    }//GEN-LAST:event_textFieldTelefonoFocusGained

    private void textFieldTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldTelefonoFocusLost
        if (textFieldTelefono.getText().trim().equals("")) {
            textFieldTelefono.setText("Teléfono");
        }

        textFieldTelefono.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldTelefonoFocusLost

    private void textFieldDireccion2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccion2FocusGained
        if (textFieldDireccion2.getText().trim().equals("Calle y Número".trim())) {
            textFieldDireccion2.setText("");
        }

        textFieldDireccion2.setForeground(Color.red);    }//GEN-LAST:event_textFieldDireccion2FocusGained

    private void textFieldDireccion2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldDireccion2FocusLost
        if (textFieldDireccion2.getText().trim().equals("")) {
            textFieldDireccion2.setText("Calle y Número");
        }

        textFieldDireccion2.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldDireccion2FocusLost

    private void textFieldColonia2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldColonia2FocusGained
        if (textFieldColonia2.getText().trim().equals("Colonia")) {
            textFieldColonia2.setText("");
        }

        textFieldColonia2.setForeground(Color.red);
    }//GEN-LAST:event_textFieldColonia2FocusGained

    private void textFieldColonia2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldColonia2FocusLost
        if (textFieldColonia2.getText().trim().equals("")) {
            textFieldColonia2.setText("Colonia");
        }

        textFieldColonia2.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldColonia2FocusLost

    private void textFieldLocalidad2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldLocalidad2FocusGained
        if (textFieldLocalidad2.getText().trim().equals("Localidad/Municipio/Delegación")) {
            textFieldLocalidad2.setText("");
        }

        textFieldLocalidad2.setForeground(Color.red);
    }//GEN-LAST:event_textFieldLocalidad2FocusGained

    private void textFieldLocalidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldLocalidad2FocusLost
        if (textFieldLocalidad2.getText().trim().equals("")) {
            textFieldLocalidad2.setText("Localidad/Municipio/Delegación");
        }

        textFieldLocalidad2.setForeground(new Color(153, 153, 255));
    }//GEN-LAST:event_textFieldLocalidad2FocusLost

    private void formattedTextFieldFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTextFieldFechaKeyTyped
        //^\d+(\/\d+)*$
        //Cosa rara para fechas
        char c = evt.getKeyChar();
        if(c < '/' || c > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_formattedTextFieldFechaKeyTyped

    private void textFieldMunicipioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldMunicipioKeyTyped
        char c = evt.getKeyChar();
        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){
            evt.consume();
        }
    }//GEN-LAST:event_textFieldMunicipioKeyTyped

    private void textFieldDelegacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldDelegacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDelegacionKeyTyped

    private void textFieldNSSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNSSKeyTyped
        //Solo números
        char c = evt.getKeyChar();
        if(c < '0' || c > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_textFieldNSSKeyTyped

    private void textFieldNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNombresKeyTyped
        //Solo letras y espacios
        char c = evt.getKeyChar();
        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z') && c > ' '){
            evt.consume();
        }
    }//GEN-LAST:event_textFieldNombresKeyTyped

    private void textFieldApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldApellidoMaternoKeyTyped
        //Solo letras
        char c = evt.getKeyChar();
        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){
            evt.consume();
        }
    }//GEN-LAST:event_textFieldApellidoMaternoKeyTyped

    private void textFieldApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldApellidoPaternoKeyTyped
        char c = evt.getKeyChar();
        if((c < 'A' || c > 'Z') && (c < 'a' || c > 'z')){
            evt.consume();
        }
    }//GEN-LAST:event_textFieldApellidoPaternoKeyTyped

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        JFrame pane = new Inicio();
        pane.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_buttonSalirActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JFormattedTextField formattedTextFieldFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelUnidad;
    private javax.swing.JTextField textFieldApellidoMaterno;
    private javax.swing.JTextField textFieldApellidoPaterno;
    private javax.swing.JTextField textFieldCURP;
    private javax.swing.JTextField textFieldClavePaciente;
    private javax.swing.JTextField textFieldColonia1;
    private javax.swing.JTextField textFieldColonia2;
    private javax.swing.JTextField textFieldDelegacion;
    private javax.swing.JTextField textFieldDireccion1;
    private javax.swing.JTextField textFieldDireccion2;
    private javax.swing.JTextField textFieldDireccionJurisdiccion;
    private javax.swing.JTextField textFieldEdad;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEntidadFederativa;
    private javax.swing.JTextField textFieldEntidadNacimiento;
    private javax.swing.JTextField textFieldEscolaridad;
    private javax.swing.JTextField textFieldInstitucion;
    private javax.swing.JTextField textFieldJurisdiccion;
    private javax.swing.JTextField textFieldLocalidad1;
    private javax.swing.JTextField textFieldLocalidad2;
    private javax.swing.JTextField textFieldMunicipio;
    private javax.swing.JTextField textFieldNSS;
    private javax.swing.JTextField textFieldNombres;
    private javax.swing.JTextField textFieldOcupacion;
    private javax.swing.JTextField textFieldServicioMedico;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JTextField textFieldUnidadMedica;
    // End of variables declaration//GEN-END:variables

    class RoundedCornerBorder extends AbstractBorder {

        private final Color ALPHA_ZERO = new Color(0x0, true);

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            Shape border = getBorderShape(x, y, width - 1, height - 1);
            g2.setPaint(ALPHA_ZERO);
            Area corner = new Area(new Rectangle2D.Double(x, y, width, height));
            corner.subtract(new Area(border));
            g2.fill(corner);
            g2.setPaint(Color.GRAY);
            g2.draw(border);
            g2.dispose();
        }

        public Shape getBorderShape(int x, int y, int w, int h) {
            int r = h; //h / 2;
            return new RoundRectangle2D.Double(x, y, w, h, r, r);
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(4, 8, 4, 8);
        }

        @Override
        public Insets getBorderInsets(Component c, Insets insets) {
            insets.set(4, 8, 4, 8);
            return insets;
        }
    }
}
